### PR TITLE
Check extension and use appropriate type

### PR DESCRIPTION
**Pull request by shumbo**
I wanted to use CLI to generate i18n files from CSV so added few changes to detect extension of the file and use "csv" or "tsv" if the extension matches.

### CODE REVIEW

**Comment by huei90** [comment]
Thanks for you PR @shumbo

I love this feature, but the test cas fails, do you mind update the test so I can pull it?

**Comment by shumbo** [comment]
Travis was failing while installing dependencies so I changed some lines to fix. Could you check this again please?

**Comment by huei90** [comment]
Nice, it works now :+1:

One more last thing, can you edit the README about this change(--hash for using it)

Then I will merge it.

Thanks again =)

**Comment by shumbo** [comment]
I just noticed that detecting extension before the checks of `-h` and `-v` made these commands unreachable, so I moved  extension detection to after them.

I'm not sure whether I've done what you exact mentioned, but I added references to this feature in README and `-h`. Because of my poor language, could you please describe what to do in easier words if I should have done in another way. Thank you.

**Comment by huei90** [comment]
This is good enough :beer:

**Comment by shumbo** [comment]
I would appreciate if you publish this change to NPM so I can use it in my project. Thank you for providing us a great tool!

**Comment by huei90** [comment]
DONE. 0.2.1 :label:

**Pull request merged**
