### PR TITLE
Do not include the key if it contains an empty string

### PR DESCRIPTION
**Pull request by gpiroux**

### CODE REVIEW

**Comment by huei90** [comment]
@gpiroux Thanks for this PR.
Would you mind execute `browserify i18n-generator.js > browser.js` to generate browser.js file?
After that I will merge it :beers:

**Comment by gpiroux** [comment]
Thanks for your quick reply ;-) 

browserify done !

**Comment by huei90** [comment]
Thanks @gpiroux 
Well done.

**Comment by huei90** [comment]
How do you think about `i18n-generator`? @gpiroux Is this useful to your project?

**Comment by gpiroux** [comment]
Hi @huei90, thanks for the merge...
Yes, I hope it will be usefull... The translator team prefer to work with csv file than with json files.

**Comment by huei90** [comment]
Thanks. `i18n-generator` also works with csv file.

**Comment by gpiroux** [comment]
Yes, it is the idea, the translation team will work with the csv file, then i18n-generator is used to generate the json files used by the angular app...

**Comment by huei90** [comment]
Yes, you are right. I should rename the description to
`i18n json files generator` rather than just `i18n generator`

**Comment by huei90** [comment]
When the team is using csv file for the translation, I don't think there need `i18n-generator`

**Comment by huei90** [comment]
This change should add a test case.

**Comment by huei90** [comment]
@gpiroux whats your experience on i18n

**Comment by gpiroux** [comment]
I'll submit a new pull request with test case.

I'm currently developing a localized angular app using angular translate. It's for that reason I need json files with the key/translation pairs.

**Comment by huei90** [comment]
Please let me know if there is another issue or suggestion, thanks!!!

**Comment by gpiroux** [comment]
Yes, sure I will !

Perhaps one thing I have in mind but it is not an issue for me, is that when closing a nested structure with "<=", the whole structure seems to be closed when there are several levels. In the example below, "global" and "people" are closed, while I would expect only "people"...  

    => global
    sleep | sleep 
    morning | morning
    => people
    Ahmad |  | Ahmad
    <=

An idea to solve this could be to use "<=" to close one level, "<==" to close 2 level ...
Just a though...

Geoffroy

**Comment by huei90** [comment]
@gpiroux your consideration is right. I didn't state that in the README file.
`<=` will close all the scope whether more than one `=>`

Here's my consideration
```
=> global
sleep | sleep 
morning | morning
=> people
Ahmad |  | Ahmad
<=

{ "global": { "sleep": "sleep", "morning": "morning", "people": { "Admad", "Ahmad" }}}
```

Add one more object "Big" in global

use

=> global
sleep | sleep 
morning | morning
big | big
=> people
Ahmad |  | Ahmad
<=

```

Object after `=> people` should consider as property within the object `people`

**Pull request merged**
